/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.GestionEmpleados;

import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Ima
 */
public class MenuGestionEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form MenuGestionEmpleados
     */
    private JPanel contenedor = null;
    
   
    public MenuGestionEmpleados(JPanel contenedor) {
        initComponents();
        this.contenedor= contenedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnModificar2 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("EMPLEADOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 10, -1, -1));

        btnModificar2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnModificar2.setText("MODIFICAR");
        btnModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar2ActionPerformed(evt);
            }
        });
        add(btnModificar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 177, 395, 90));

        btnEliminar.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 371, 395, 90));

        btnAgregar.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, 395, 90));

        btnBuscar.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 274, 395, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar2ActionPerformed
       limpiarContenido();
		contenedor.removeAll();
		contenedor.add(new Interfaces.GestionEmpleados.ContenedorModificarEmpleado(contenedor));
		actualizarContenido();
        
    }//GEN-LAST:event_btnModificar2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

           limpiarContenido();
		contenedor.removeAll();
		contenedor.add(new Interfaces.GestionEmpleados.ContenedorEliminarEmpleado(contenedor));
		actualizarContenido();
        
            
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        
        limpiarContenido();
		contenedor.removeAll();
		contenedor.add(new Interfaces.GestionEmpleados.ContenedorAgregarEmpleado(contenedor));
		actualizarContenido();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    
        
        
        limpiarContenido();
		contenedor.removeAll();
		contenedor.add(new Interfaces.GestionEmpleados.ContenedorBuscarEmpleado(contenedor));
		actualizarContenido();
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    
public void limpiarContenido() {
	Component componente = contenedor.getComponent(0);
	contenedor.remove(componente);
	actualizarContenido();
}

public void actualizarContenido() {
	contenedor.revalidate();
	contenedor.repaint();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnModificar2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
