
package Interfaces.GestionPedidoCliente;

import java.awt.Component;
import javax.swing.JPanel;


public class MenuPedidoCliente extends javax.swing.JPanel {

   
    JPanel contenedorPrincipal = null;
    
    public MenuPedidoCliente(JPanel contenedorPrincipal) {
        initComponents();
        this.contenedorPrincipal = contenedorPrincipal;
    }
    
    
    public void limpiarContenido() {
	Component componente = contenedorPrincipal.getComponent(0);
	contenedorPrincipal.remove(componente);
	actualizarContenido();
       }

    public void actualizarContenido() {
	contenedorPrincipal.revalidate();
	contenedorPrincipal.repaint();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgrTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnEstadoP = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();

        backgrTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblTitulo.setText("Gestión de pedido cliente ");
        backgrTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 0, -1, 70));

        btnRegistrar.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        btnRegistrar.setText("Agregar ");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEstadoP.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        btnEstadoP.setText("Estado de pedido");
        btnEstadoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoPActionPerformed(evt);
            }
        });

        btnVolverMenu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 11)); // NOI18N
        btnVolverMenu.setText("Volver al menú");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgrTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstadoP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolverMenu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgrTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstadoP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnVolverMenu)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        
        limpiarContenido();
        contenedorPrincipal.removeAll();
        contenedorPrincipal.add(new Interfaces.GestionPedidoCliente.Regristrar());
        actualizarContenido();
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEstadoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoPActionPerformed
        
        
        limpiarContenido();
        contenedorPrincipal.removeAll();
        contenedorPrincipal.add(new Interfaces.GestionPedidoCliente.EstadoPedido());
        actualizarContenido();
        
    }//GEN-LAST:event_btnEstadoPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgrTitulo;
    private javax.swing.JButton btnEstadoP;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
