/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.GestionUsuarios;

import Clases.Usuario;
import Manejadores.ManejadorGUsuarios.ManejadorGUsuarios;
import Manejadores.Principal;
import java.awt.Component;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ima
 */
public class contenedorEliminarUsuario extends javax.swing.JPanel {

    private JPanel contenedor = null;
    private ManejadorGUsuarios consultasusuarios;
    private Principal conectorBDUsuario = new Principal();
    private List< Usuario> resultados;
    private Usuario usuarioActual;
    private DefaultTableModel tablaUsuario = new DefaultTableModel();
    private ResultSet conjuntoUsuarios;
    int filas;

    public contenedorEliminarUsuario(JPanel contenedor) {
        initComponents();
        consultasusuarios = new ManejadorGUsuarios();
        this.contenedor = contenedor;
        filas = tablaUsuario.getRowCount();
        for (int i = filas - 1; i >= 0; i--) {
            tablaUsuario.removeRow(i);
        }
        tablaUsuario.addColumn("usuario");
        tablaUsuario.addColumn("contrasena");
        tablaUsuario.addColumn("contrasenaRecuperar");
        this.tablaUsuarios.setModel(tablaUsuario);
        cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel1.setText("ELIMINAR USUARIO");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Usuario:");

        usuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        tablaUsuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contrasena", "contrasenaRecuperar"
            }
        ));
        jScrollPane2.setViewportView(tablaUsuarios);

        btnEliminar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnSalir.setText("Regresar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel9)
                .addGap(43, 43, 43)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnEliminar))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int resultado = consultasusuarios.borrarUsuario(usuario.getText());
        if (resultado == 1) {
            JOptionPane.showMessageDialog(this, "Se elimino exitosamente");
            usuario.setText("");
            cargarUsuarios();
        } else {
            JOptionPane.showMessageDialog(this, "Empleado no encontrado");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        limpiarContenido();
        contenedor.removeAll();
        contenedor.add(new Interfaces.GestionUsuarios.MenuGestionUsuario(contenedor));
        actualizarContenido();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void limpiarContenido() {
        Component componente = contenedor.getComponent(0);
        contenedor.remove(componente);
        actualizarContenido();
    }

    public void actualizarContenido() {
        contenedor.revalidate();
        contenedor.repaint();
    }

    public void cargarUsuarios() {
        try {
            filas = tablaUsuario.getRowCount();
            System.out.println("numero de filas: " + filas);
            for (int i = filas - 1; i >= 0; i--) {
                tablaUsuario.removeRow(i);
            }
            CallableStatement cts = consultasusuarios.getDbConection().getConexion().prepareCall("SELECT * FROM Usuario");
            System.out.println("consulta realizada");
            ResultSet r = cts.executeQuery();
            while (r.next()) {
                Object dato[] = new Object[3];
                for (int columnas = 0; columnas < 3; columnas++) {
                    dato[columnas] = r.getString(columnas + 1);
                }
                tablaUsuario.addRow(dato);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
