/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.GestionVenta;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

/**
 *
 * @author César Abarca
 */
public class Venta extends javax.swing.JPanel {

    
    
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("HH:mm:ss");
    int numero;
            
            public Consultas CC;
    
    DefaultTableModel tabla = new DefaultTableModel();
    DefaultTableModel tabla2 = new DefaultTableModel();
    int filas;
    private ResultSet conjuntoInstalacion;
   
    
    public Venta() throws SQLException {
        initComponents();
        txtFecha.setText(dtf.format(LocalDateTime.now()));
        txtHora.setText(dtf2.format(LocalDateTime.now()));
        
        
        txtIdVenta.setText(String.valueOf(numero = (int)(Math.random()*1000+1)));
        CC=new Consultas();
        cargarCombobox ();
       AgregarVenta();
     
        
         filas = tabla2.getRowCount();
        for(int i=filas-1;i>=0;i--){
            tabla2.removeRow(i);}
        tabla2.addColumn("Nombre Producto");        
        tabla2.addColumn("Cantidad");        
        tabla2.addColumn("Total");        
        
        this.jTable1.setModel(tabla2);
        
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdVenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgregarLista = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnBuscarPrecioProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        btnGenerarTicket = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Panton Rust Heavy Gr Sh", 0, 36)); // NOI18N
        jLabel1.setText("Registrar   Venta");

        txtFecha.setEditable(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Fecha:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("ID:");

        txtIdVenta.setEditable(false);

        jLabel4.setText("Producto:");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Precio:");

        txtPrecio.setEditable(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        btnAgregarLista.setText("Agregar a la Lista");
        btnAgregarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarListaActionPerformed(evt);
            }
        });

        jLabel7.setText("Total:");

        txtTotal.setEditable(false);

        btnBuscarPrecioProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnBuscarPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrecioProductoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Producto", "Cantidad", "Total $"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("Total a Pagar: ");

        txtTotalPagar.setEditable(false);

        lblHora.setText("Hora:");

        txtHora.setEditable(false);

        btnGenerarTicket.setText("Generar Ticket");
        btnGenerarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnAgregarLista))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHora)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnBuscarPrecioProducto))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                .addComponent(txtHora, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGenerarTicket)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHora)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btnBuscarPrecioProducto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(btnAgregarLista)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnGenerarTicket)
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarListaActionPerformed
        
        modificarStock();
    }//GEN-LAST:event_btnAgregarListaActionPerformed

    private void btnBuscarPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrecioProductoActionPerformed
       
       int cantidad;
       float tot=(float) 0.0;
       cantidad=Integer.parseInt(txtCantidad.getText());
     
       conjuntoInstalacion = CC.BuscaProducto(txtProducto.getSelectedItem().toString());
            filas = tabla.getRowCount();
            for(int i=filas-1; i>=0;i--){
                tabla.removeRow(i);
            }
        try{
            while(conjuntoInstalacion.next()){
                Object dato[] = new Object[10];
                for(int i=0; i<10;i++){
                    dato[0]=conjuntoInstalacion.getString("id");
                    dato[1]=conjuntoInstalacion.getString("descripcion");
                    dato[2]=conjuntoInstalacion.getString("precio");
                    dato[3]=conjuntoInstalacion.getString("stock");
                    dato[4]=conjuntoInstalacion.getString("idProveedor");
                    
                   //Checar el dato del precio por que no nos esta retornando el valor
                   //Checar el valor de dato[2]    
                }
                txtPrecio.setText((String) dato[2]);
           
                tot=Float.parseFloat((String) dato[2]);
                 txtTotal.setText( String.valueOf(tot*cantidad) );
                 
                
           
            
               
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_btnBuscarPrecioProductoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnGenerarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTicketActionPerformed
        
        File archivo= new File(System.getProperty("user.home") + "/Desktop/"+"Venta "+txtIdVenta.getText()+".pdf");
        System.out.println(System.getProperty("user.home"));
        
        
             generarPDF(archivo,getTabla());
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
           
            
  try {
    Desktop.getDesktop().browse(new URI("file:/" + "/" + "/" + archivo.getAbsolutePath().replace("\\", "/")));
  } catch (URISyntaxException ex) {
    
  } catch (IOException ex) {
   
  }
}
        
        
        
    }//GEN-LAST:event_btnGenerarTicketActionPerformed

    
     private ArrayList <Producto_Venta> cargarProducto(){
        ArrayList <Producto_Venta> lista =  new ArrayList<>();
        try{
            CallableStatement cts = CC.getConexion().prepareCall("SELECT*FROM producto");
            ResultSet r = cts.executeQuery();
            while(r.next()){
                Producto_Venta listatemporal = new Producto_Venta(r.getString(1) , 
                r.getString(2),
                r.getString(3),
                r.getString(4),
                r.getString(5));
                lista.add(listatemporal);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return lista;
    }
     
     
     
     
     
     
     
     private void cargarCombobox (){
        ArrayList<Producto_Venta> list = cargarProducto();
       // ArrayList<Tecnico> listT = cargarTecnicos();
        //ArrayList<Integer> listInst = cargarInstalaciones();
        //ArrayList<Equipo> listE = cargarEquipo();
        //ArrayList<Desinstalacion> listIntsD =  cargarDesinstalaciones();
        //String folio;
        for (int i = 0; i < list.size(); i++) {
            txtProducto.addItem(list.get(i).getDescripcion());
            
            
        }
        
        
        /*
        for (int i = 0; i < listIntsD.size(); i++) {
            int folioT = listIntsD.get(i).getFolioDes();
            folio = Integer.toString(folioT);
            cmbxFolioDesinst.addItem(folio);
        }
        
        for (int i = 0; i < listInst.size(); i++) {
            int folioI = listInst.get(i);
            folio = Integer.toString(folioI);
            cmbxFolioInst.addItem(folio);
        }
        
        for (int i = 0; i < listE.size(); i++) {
            cmbxEquipoInst.addItem(listE.get(i).getNombreE());
            cmbxEqDesinst.addItem(listE.get(i).getNombreE());
        }*/
        
    }
     
     
     
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLista;
    private javax.swing.JButton btnBuscarPrecioProducto;
    private javax.swing.JButton btnGenerarTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JComboBox<String> txtProducto;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables

public void AgregarVenta(){

    if(txtIdVenta.getText().isEmpty()||txtFecha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
        }else{
            int resultado = CC.agregarVenta(Integer.parseInt(txtIdVenta.getText()), txtFecha.getText());
        if(resultado == 1){
            
           
         
        }else
            JOptionPane.showMessageDialog(this, "No se pudo agregar la Venta");
        }   
}


public void AgregarDetalleVenta(){

     conjuntoInstalacion = CC.BuscaProducto(txtProducto.getSelectedItem().toString());
            filas = tabla.getRowCount();
            for(int i=filas-1; i>=0;i--){
                tabla.removeRow(i);
            }
        try{
            while(conjuntoInstalacion.next()){
                Object dato[] = new Object[5];
                for(int i=0; i<5;i++){
                    dato[0]=conjuntoInstalacion.getString("id");
                    dato[1]=conjuntoInstalacion.getString("descripcion");
                    dato[2]=conjuntoInstalacion.getString("precio");
                    dato[3]=conjuntoInstalacion.getString("stock");
                    dato[4]=conjuntoInstalacion.getString("idProveedor");
                    
                   //Checar el dato del precio por que no nos esta retornando el valor
                   //Checar el valor de dato[2]    
                }
                
           
               
                 
               if(txtIdVenta.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
        }else{
            int resultado = CC.agregarDetalleVenta((String) dato[0],txtIdVenta.getText(),txtCantidad.getText(),
                    txtPrecio.getText(),txtTotal.getText());
        if(resultado == 1){
            
            JOptionPane.showMessageDialog(this, "Se agrego con Éxito");
         
        }else
            JOptionPane.showMessageDialog(this, "No se pudo agregar el Detalle Venta");
        } 
           
            
               
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        
        
}

    public void AgregarLista(){
    
        float sum=(float) 0.0;
        float total=(float) 0.0;
        String var="";
        conjuntoInstalacion = CC.consultaLista(txtIdVenta.getText());
            filas = tabla2.getRowCount();
            for(int i=filas-1; i>=0;i--){
                tabla2.removeRow(i);
                
            }
        try{
            while(conjuntoInstalacion.next()){
                Object dato[] = new Object[3];
                for(int i=0; i<3;i++){
                    dato[0]=conjuntoInstalacion.getString("descripcion");
                    dato[1]=conjuntoInstalacion.getString("cantidad");
                    dato[2]=conjuntoInstalacion.getString("total");
                    
                   
                var=String.valueOf(dato[2]);
                sum=Float.parseFloat(var);
                
                }
               total+=sum; 
                tabla2.addRow(dato);
                
                
                txtTotalPagar.setText(String.valueOf(total));
                
                
               
                
               
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    
    public void modificarTotalVenta(){
    
        
            int resultado = CC.modificarTotalVenta(txtTotalPagar.getText(), txtIdVenta.getText());
            
        if(resultado == 1){
            
           
        }else
            JOptionPane.showMessageDialog(this, "No se pudo modificar la Instalacion");
        
        
    }
    
    
    public void modificarStock(){
    
        
            int resultado = CC.modificarStockProducto(txtCantidad.getText(), txtProducto.getSelectedItem().toString());
            
        if(resultado == 1){
            
             AgregarDetalleVenta();
            AgregarLista();
            modificarTotalVenta();
           
        }else
            JOptionPane.showMessageDialog(this, "No se puede agregar el producto"
                    +"\n Debido a que no cuenta con suficientes productos","Error",
                    JOptionPane.ERROR_MESSAGE);
        
        
        
    }
    
    
    
    
   
    
    
    private void generarPDF(File archivo, String informacion) {
//Tamaño del ancho del papel A7 
//Ancho:  74mm == 209.76 pt
//Largo: 104mm == 294.80 pt
	try {
		PDDocument documento = new PDDocument();
		PDPage pagina = new PDPage(new PDRectangle(209.76f, 294.80f));

		documento.addPage(pagina);

		PDPageContentStream contenido = new PDPageContentStream(documento, pagina);

		contenido.beginText();
		contenido.setFont(PDType1Font.HELVETICA, 7);
		contenido.newLineAtOffset(10, pagina.getMediaBox().getHeight() - 10);
		contenido.setLeading(10.0f);

		contenido.showText("                      ---[ Tienda de Abarrotes Edwin ]---");
		contenido.newLine();
		contenido.showText("Fecha: " + txtFecha.getText() + "                                  Hora: " + txtHora.getText());
		contenido.newLine();
		contenido.showText("                                   Ticket de Venta");
		contenido.newLine();

		//Aqui se recorre todo el contenido del
		//documento en busca de saltos de linea
		//para insertar las nuevas lineas cada
		//que se encuentren.
		String contenidoInsertar = "";
		for (char caracter : informacion.toCharArray()) {
			if (caracter == '\n') {
				//Se inserta el contenido cada que se encuentra un salto de linea
				contenido.showText(contenidoInsertar);
				contenido.newLine();
				contenidoInsertar = "";
			} else {
				contenidoInsertar += caracter;
			}
		}

		//Si al final sale del ciclo pero no hay un salto de linea
		//(caracter que sirve para insertar los datos) se debería 
		//de ejecutar esto, verifica si todavía hay contenido sin insertar.
		if (contenidoInsertar != "") {
			contenido.showText(contenidoInsertar);
			contenido.newLine();
			contenidoInsertar = "";
		}
		contenido.showText("                                                                          Total: $" + txtTotalPagar.getText());

		contenido.newLine();
		
		contenido.newLine();
		contenido.newLine();
		
		contenido.endText();
		contenido.close();

		documento.save(archivo);

	} catch (Exception error) {
		JOptionPane.showMessageDialog(this, "Error al generar el PDF", "Error", ERROR);
                
                
                           
	}
}

    
    
    public String getTabla(){
    String contenido="Producto Cantidad  Total $\n";
        //Recorre Filas
        for(int i=0;i<tabla2.getRowCount();i++){
        
            
            //Recorre Columnas
            for(int j=0;j<tabla2.getColumnCount();j++){
                
                contenido+=tabla2.getValueAt(i, j);
            contenido+="       ";
            
            }
            contenido+="\n";
        }
        
    return contenido;   
    }
    

    
}
