
package Interfaces.GestionPedidoProveedor;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class MenuGestionPedido extends javax.swing.JPanel {

    /**
     * Creates new form MenuGestionPedido
     */
    public MenuGestionPedido() {
        initComponents();
        SetImageLabel(lblLogo ,"C:\\Users\\PC\\Downloads\\ProyectoMau\\TiendaEdwin\\src\\img\\logo gestionp.png");
    }
    
    //Creación del método para acomodar imagenes
     private void SetImageLabel(JLabel labelName, String root){
           
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
        image.getImage().getScaledInstance(labelName.getWidth() ,labelName.getHeight() , Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JButton();
        background1 = new javax.swing.JPanel();
        panelTitulo1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();

        background.setBackground(java.awt.SystemColor.activeCaption);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleBackground"));

        lblTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblTitulo.setText("Gestión de pedido");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        btnVisualizar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnVisualizar.setText("Visualizar");
        background.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 220, 30));

        background1.setBackground(java.awt.SystemColor.activeCaption);
        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo1.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleBackground"));

        lblTitulo1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lblTitulo1.setText("Gestión de pedido");

        javax.swing.GroupLayout panelTitulo1Layout = new javax.swing.GroupLayout(panelTitulo1);
        panelTitulo1.setLayout(panelTitulo1Layout);
        panelTitulo1Layout.setHorizontalGroup(
            panelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitulo1Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTitulo1Layout.setVerticalGroup(
            panelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(lblLogo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background1.add(panelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        btnGenerar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnGenerar.setText("Generar");
        background1.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 220, 30));

        background.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnModificar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");
        background.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 220, 30));

        btnEliminar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        background.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 220, 30));

        btnVolverMenu.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        btnVolverMenu.setText("Volver al menú");
        background.add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel background1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTitulo1;
    // End of variables declaration//GEN-END:variables
}
