/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces.GestionProducto;

import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author luis
 */
public class PanelMenuGestionProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuGestionProducto
     */
    
    private JPanel contenedor = null;

    public PanelMenuGestionProducto(JPanel contenedor) {
        initComponents();
        this.contenedor = contenedor;
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarNuevoProducto = new javax.swing.JButton();
        btnEliminarProductos = new javax.swing.JButton();
        btnModificarProductos = new javax.swing.JButton();

        btnAgregarNuevoProducto.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnAgregarNuevoProducto.setText("AGREGAR NUEVO PRODUCTO");
        btnAgregarNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNuevoProductoActionPerformed(evt);
            }
        });

        btnEliminarProductos.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnEliminarProductos.setText("ELIMINAR PRODUCTOS");
        btnEliminarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductosActionPerformed(evt);
            }
        });

        btnModificarProductos.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnModificarProductos.setText("MODIFICAR PRODUCTOS");
        btnModificarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevoProductoActionPerformed
        // TODO add your handling code here:
        limpiarContenido();
        contenedor.add(new PanelAgregarProducto());
        actualizarContenido();
    }//GEN-LAST:event_btnAgregarNuevoProductoActionPerformed

    private void btnModificarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductosActionPerformed
        // TODO add your handling code here:
         limpiarContenido();
        contenedor.add(new PanelModificar_VisualizarProductos());
        actualizarContenido();
    }//GEN-LAST:event_btnModificarProductosActionPerformed

    private void btnEliminarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductosActionPerformed
        // TODO add your handling code here:
         limpiarContenido();
        contenedor.add(new PanelEliminarProducto());
        actualizarContenido();
    }//GEN-LAST:event_btnEliminarProductosActionPerformed

    private void setInterfaz(JPanel interfazMostrar) {
    limpiarContenido();
    contenedor.removeAll();
    contenedor.add(interfazMostrar);
    actualizarContenido();
}
     

    public void limpiarContenido() {
    Component componente = contenedor.getComponent(0);
    contenedor.remove(componente);
    actualizarContenido();
}

public void actualizarContenido() {
    contenedor.revalidate();
    contenedor.repaint();
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNuevoProducto;
    private javax.swing.JButton btnEliminarProductos;
    private javax.swing.JButton btnModificarProductos;
    // End of variables declaration//GEN-END:variables


}
